[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chat"
version = "0.1.0"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "httpx",
  "weaviate-client",
  "pydantic",
  "python-dotenv"
]

[tool.setuptools]
py-modules = ["app"]
